dataset:
  path: data/DeFlow_Dataset/
  val_ids: data/val_ids.txt
  test_ids: data/test_ids.txt
  max_depth: 100.0
  min_depth: 5.0
  bbox:
  - -3.6073
  - -2.87778
  - -6.36487
  - 3.67776
  - 11.4507
  - -5.19944
  crop_image: []
  depth_input_ratio: 0.5
misc:
  use_gpu: true
  seed: 1124
  mode: eval
  ckpt_path: checkpoints/
optimizer:
  learning_rate: 0.0004
  weight_decay: 0.0
  momentum: 0.8
  beta_1: 0.9
  beta_2: 0.999
scheduler:
  name: MultiStepLR
  gamma: 0.5
  milestones:
  - 5
  - 10
  - 18
Adam:
  learning_rate: 0.0004
  weight_decay: 0.0
  momentum: 0.8
  beta_1: 0.9
  beta_2: 0.999
SGD:
  learning_rate: 0.01
  weight_decay: 0.0001
  momentum: 0.9
  nesterov: true
train:
  num_workers: 8
  max_epoch: 30
  n_verbose: 99
  shuffle: true
  iter_size: 4
  batch_size: 2
  grad_clip: 1.0
  compute_depth: true
  epoch_depth: 1
val:
  num_workers: 8
  batch_size: 1
test:
  num_workers: 8
  batch_size: 1
loss:
  smooth_derivative: second
  photometric_loss: ssim
  pyramid_weights:
  - 8.0
  - 4.0
  - 2.0
  - 1.0
  - 1.0
  depth_weight: 0.1
  flow_weight: 0.9
  flow_photo_w: 0.85
  depth_l1_w: 0.9
  photo_max_d: 1
  depth_data_loss: L1
network:
  num_channels:
  - 3
  - 32
  - 64
  - 96
  - 128
  - 192
  search_range: 4
  output_level: 4
  input_depth: true
  depth_channels:
  - 1
  - 8
  - 16
  - 24
  - 32
  - 64
wandb: true
augmentation:
  enabled: true
  flip_mode: lr
  crop_size:
  - 960
  - 640
